name: build-deploy-from-public

on:
 push:
  branches: [ "master" ]
      
 pull_request:
  branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 
permissions:
 id-token: 'write'
 pages: 'write'
      
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - name: Checkout
     uses: actions/checkout@v4
     with:
      ref: master
      submodules: recursive
     
   - name: Setup Node.js
     uses: actions/setup-node@v4.0.2
     with:
      node-version: 20

   - name: Install dependencies
     run: npm install react-scripts --save

   - name: Build with npm
     run: npm run build
      
   - name: Upload artifact for deployment job
     uses: actions/upload-pages-artifact@v3
     with:
      path: ./build/_site
      name: github-pages
      retention-days: 1
     
      
 deploy:
  runs-on: ubuntu-latest
  
  needs: build
  
  steps:
   - name: Deploy to Github Page
     id: deployment
     uses: actions/deploy-pages@v4

  environment:
   name: github-pages
   url: ${{ steps.deployment.outputs.page_url }}
