name: build-deploy-from-public

on:
  push:
    branches: [ "master" ]
      
  pull_request:
    branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
      
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Change to app directory
        run: |
          pwd
          cd ../
          ls

      - name: Install dependencies
        run: npm install
          
      - name: Build 
        run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: npm run deploy


