name: build-deploy-from-public

on:
 push:
  branches: [ "master" ]
      
 pull_request:
  branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 
permissions:
 id-token: 'write'
 pages: 'write'
      
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - name: Checkout
     uses: actions/checkout@v4
     with:
      ref: master
      submodules: recursive
     
   - name: Build with Jekyll
     uses: actions/jekyll-build-pages@v1
     with:
      source: ./public
      destination: ./public/_site
      future: false
      
   - name: Upload artifact for deployment job
     uses: actions/upload-pages-artifact@v3
     with:
      path: ./public/_site
      name: github-pages
      retention-days: 1
     
   - uses: actions/upload-artifact@v4
     with:
      name: github-pages
      path: /home/runner/work/_temp/artifact.tar
      retention-days: 1
      if-no-files-found: error
      compression-level: 6
      overwrite: false

      
 deploy:
  runs-on: ubuntu-latest
  
  needs: build
  
  steps:
   - name: Deploy to Github Page
     id: deployment
     uses: actions/deploy-pages@v4

  environment:
   name: github-pages
   url: ${{ steps.deployment.outputs.page_url }}
