name: build & deploy from /public

on:
 push:
  branches: [ "master" ]
      
 pull_request:
  branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 
permissions:
 id-token: 'write'
 pages: 'write'
      
jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [20.x]
  
  steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - uses: actions/checkout@v4
     with:
      ref: master
      submodules: recursive
     
   - name: Build with Jekyll
     uses: actions/jekyll-build-pages@v1
     with:
      source: ./public
      destination: ./public/_site
      future: false
      
   - name: Upload artifact for deployment job
     uses: actions/upload-pages-artifact@v3
     with:
      path: ./public/_site
      name: github-pages
      retention-days: 1
     
 deploy:
  runs-on: ubuntu-latest
  needs: build
  
  steps:

   - name: Deploy to Github Page
     id: deployment
     uses: actions/deploy-pages@v4

  environment:
   name: github-pages
   url: ${{ steps.deployment.outputs.page_url }}
