name: build-deploy-from-public

on:
  push:
    branches: [ "master" ]
      
  pull_request:
    branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
      
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
          
      - name: Build 
        run: npm run build

      - name: Set url
        run: |
          echo ${{ vars.SET_URL_TOKEN }}
          git remote set-url origin https://datle2001:${{ vars.SET_URL_TOKEN }}@github.com/datle2001/my-app

      - name: Deploy
        run: npm run deploy
          
      


