name: build-deploy-from-public

on:
  push:
    branches: [ "master" ]
      
  pull_request:
    branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
permissions:
  contents: 'write'
      
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
        
      - name: Install dependencies
        run: npm install
          
      - name: Build 
        run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        

