name: learn-to-build-deploy

on:
  push:
    branches: [ "master" ]
      
  pull_request:
    branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
      
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Make a copy 404.html from index.html
        run: |
          npm i -g shx --dev
          cd public
          shx cp index.html 404.html
          ls
          
      - name: Build 
        run: npm run build

      

      - name: Print current directory
        run: ls
        
      - name: Deploy to gh-pages
        run: |
          git config user.email ${{ secrets.CONFIG_EMAIL }}
          git config user.name ${{ secrets.CONFIG_NAME }}
          git remote set-url origin https://datle2001:${{ secrets.PAT }}@github.com/datle2001/my-app.git
          npm run deploy
          
      


